### ISSUE TITLE
Create NMEA messages

### ISSUE THREAD

**Issue by bergtwvd** [tbsalling/aisutils#2]
It would be great to also have the ability to create NMEA messages, e.g. from data provided by a simulator. These (simulated) NMEA messages can then be fed to the tracker.

It seems that the present software version does not support this.  Is this something that will be added?
Or do you have a pointer to another library I can use for this, and connect up with the tracker ?

**Comment by tbsalling** [comment]
hi @bergtwvd - there are no current plans to make aismessages create NMEA armoured AIS messages. But I am also a committer to a parallel project, owned by the Danish Maritime Authority, which supports creation of NMEA strings. Have a look here: https://github.com/dma-ais/AisLib

**Comment by bergtwvd** [comment]
Thanks. I went over to the other project and there is a query on this very same topic.
https://github.com/dma-ais/AisLib/issues/32
Any suggestions?

**Comment by tbsalling** [comment]
Yes - give it a shot. AisLib, *can* definitely produce NMEA strings. The question there is about how - but with some effort I am sure you can make it work.
